#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0-or-later

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  get_date=""
  input_type=""
  output_type=""
  retrieval_mode=""
  db_path=""
  selection_method=""
  api_key=""
  target_chain=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    "jq"
  # _check_cmd \
  #   'evm-contract-call' \
  #   'evm-contract-tools'
  _check_cmd \
    "shuf" \
    "coreutils"
}

_db_path_check() {
  local \
    _db="${1}" \
    _msg=()
  if [[ ! -e "${_db}" ]]; then
    _msg=(
      "Database at"
      "${_db} does not exist."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
}

_dequote() {
  _string="${1}"
  echo \
    "${_string:1:-1}"
}

_filter_by_get() {
 local \
   _key="${1}" \
   _value="${2}"
  _filter=(
    ".[] |"
      "select("
        ".${_key} == ${_value} )"
  )
  echo \
    "${_filter[*]}"
}

_filter_get() {
  local \
    _key="${1}" \
    _value="${2}" \
    _output_type="${3}"
  echo \
    "$(_filter_by_get \
         "${_key}" \
         "${_value}").${_output_type}"
}

_filter_rpc_no_api_key_get() {
  local \
    _filter=()
  _filter=(
      ".[] |"
        "select("
          "contains("
            "\"API_KEY\" ) |"
            "not)"
  )
  echo \
    "${_filter[*]}"
}

_rpc_filter_api_key() {
  local \
    _rpcs_string="${1}" \
    _api_key="${2}" \
    _filter
  if [[ "${_api_key}" == "y" ]]; then
    _rpcs=( $( \
      echo \
        "${_rpcs_string}" | \
        jq \
          -c \
          ".[]")
    )
  elif [[ "${_api_key}" == "n" ]]; then
    _filter="$( \
      _filter_rpc_no_api_key_get)"
    readarray -t _rpcs <<< "$( \
      echo \
        "${_rpcs_string}" | \
        jq \
          -c \
          "${_filter}")"
  fi
}

_rpc_select() {
  local \
    _selection_method="${1}" \
    _rpcs=() \
    _index \
    _length
  shift \
    1
  _rpcs=(
    "$@"
  )
  if [[ "${_selection_method}" == "kirsh" ]]; then
    _index="0"
  elif [[ "${_selection_method}" == "random" ]]; then
    _length="${#_rpcs[@]}"
    _index="$( \
      shuf \
        -i \
          "0-$((${_length} -1))" \
        -n \
          1)"
  fi
  _dequote \
    "${_rpcs[${_index}]}"
}

_rpc_get() {
  local \
    _rpcs_string="${1}" \
    _api_key="${2}" \
    _selection_method="${3}"
  _rpc_filter_api_key \
    "${_rpcs_string}" \
    "${_api_key}"
  _rpc_select \
    "${_selection_method}" \
    "${_rpcs[@]}"
}

_db_get(){
  local \
    _db_path="${1}" \
    _input_type="${2}" \
    _output_type="${3}" \
    _selection_method="${4}" \
    _api_key="${5}" \
    _target_chain="${6}" \
    _filter \
    _rpcs=() \
    _length \
    _index \
    _cmd=()
  _filter_output_type="${_output_type}"
  if [[ "${_input_type}" == "id" ]]; then
    _filter_key="chainId"
    _filter_value="${_target_chain}"
  elif [[ "${_input_type}" == "name" ]]; then
    _filter_key="name"
    _filter_value="\"${_target_chain}\""
  fi
  if [[ "${_output_type}" == "id" ]]; then
    _filter_output_type="chainId"
  fi
  _filter="$( \
    _filter_get \
      "${_filter_key}" \
      "${_filter_value}" \
      "${_filter_output_type}")"
  _results_string="$( \
    cat \
      "${_db_path}" | \
      jq \
        "${_filter}")"
  if [[ "${_output_type}" == "rpc" ]]; then
    _rpc_get \
      "${_results_string}" \
      "${_api_key}" \
      "${_selection_method}"
  elif [[ "${_output_type}" == "name" ]]; then
  _dequote \
    "${_results_string}"
  elif [[ "${_output_type}" == "id" ]]; then
    echo \
      "${_results_string}"
  fi
}

_evm_chains_info() {
  local \
    _input_type="${1}" \
    _output_type="${2}" \
    _retrieval_mode="${3}" \
    _db_path="${4}" \
    _selection_method="${5}" \
    _api_key="${6}" \
    _target_chain="${7}"
  shift \
    7
  _opts+=(
    "$@"
  )
  if [[ "${_retrieval_mode}" == "offline" ]]; then
    _db_path_check \
      "${_db_path}"
    _db_get \
      "${_db_path}" \
      "${_input_type}" \
      "${_output_type}" \
      "${_selection_method}" \
      "${_api_key}" \
      "${_target_chain}"
  elif [[ "${_retrieval_mode}" != "offline" ]]; then
    _msg=(
      "unknown retrieval mode '${_retrieval_mode}'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
}

_db_path_auto_detect() {
  local \
    _lib \
    _chains \
    _db \
    _db_user \
    _msg=()
  _lib="$( \
    _get_lib)"
  _chains="evm-chains/chains.json"
  _db="${_lib}/${_chains}"
  if [[ ! -e "${_db}" ]]; then
    _db_user="${HOME}/.config/${_chains}"
    _msg=(
      "System database '${_db}'"
      "not found, trying '${_db_user}'"
    )
    _msg_info \
      "${_msg[*]}"
    if [[ ! -e "${_db_user}" ]]; then
     _msg=(
       "User database '${_db_user}'"
       "not found too!'"
     )
    _msg_error \
      "${_msg[*]}" \
      1
    fi
    _db="${_db_user}"
  fi
  _set_override \
   "db" \
   "path" \
   "${_db}"
}

_set_overrides() {
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "get" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "input" \
    "type" \
    "id"
  _set_override \
    "output" \
    "type" \
    "name"
  _set_override \
    "retrieval" \
    "mode" \
    "offline"
  _set_override \
    "selection" \
    "method" \
    "kirsh"
  _set_override \
    "api" \
    "key" \
    "n"
  _db_path_auto_detect
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Returns info about EVM blockchains.

Usage:
  $(_get "app" "name")
    [options]
    <target_chain]

  options:
     -i <input_type>        Input type. It can be 'id' or 'name'
                            Default: '$(_get "input" "type")'
     -o <output_type>       Output type. It can be 'id', 'name'
                            or 'rpc'.
                            Default: '$(_get "output" "type")'
     -m <retrieval_mode>    It can be 'offline'.
                            Default: '$(_get "retrieval" "mode")'
     -d <db_path>           Path of the chains' info json file
                            to be used for 'offline' retrieval
                            mode.
                            Default: '$(_get "db" "path")'
     -s <selection_method>  When output type is 'rpc', 
                            selection criterion to use when
                            more than one is available.
                            It can be 'kirsh' or 'random'.
                            Default: '$(_get "selection" "method")'
     -k                     Whether to include, when output type
                            is 'rpc', the ones requiring an api key.
                            Default: '$(_get "api" "key")'

     -h                     This message.
     -c                     Enable color output
     -v                     Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit}"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                 Get date:   $(_get "get" "date")"
  _msg_info "               Input type:   $(_get "input" "type")"
  _msg_info "              Output type:   $(_get "output" "type")"
  _msg_info "           Retrieval mode:   $(_get "retrieval" "mode")"
  _msg_info "            Database path:   $(_get "db" "path")"
  _msg_info "                  API Key:   $(_get "api" "key")"
  _msg_info "     RPC selection method:   $(_get "selection" "method")"
  _msg_info "             Target chain:   $(_get "target" "chain")"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2034
while \
  getopts \
    'i:o:m:d:s:kcvh?' \
    arg; do
  case \
    "${arg}" in
    i) override_input_type="${OPTARG}" ;;
    o) override_output_type="${OPTARG}" ;;
    m) override_retrieval_mode="${OPTARG}" ;;
    d) override_db_path="${OPTARG}" ;;
    s) override_selection_method="${OPTARG}" ;;
    k) override_api_key="y" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( $# < 1)); then
  _msg_error \
    "no chain identifier given", \
    0
  _set_overrides
  _usage \
    1
fi
_set \
  "target" \
  "chain" \
  "${1}"
_set_overrides
_config_user_init \
  "$( \
    _get \
      "app" \
      "name")"
_show_config
app_opts=(
  "$(_get \
       "input" \
       "type")"
  "$(_get \
       "output" \
       "type")"
  "$(_get \
       "retrieval" \
       "mode")"
  "$(_get \
       "db" \
       "path")"
  "$(_get \
       "selection" \
       "method")"
  "$(_get \
       "api" \
       "key")"
  "$(_get \
       "target" \
       "chain")"
)
_evm_chains_info \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
